ALTER TABLE SURVEY_ANSWER DROP CONSTRAINT FK_SA_SURVEY;
ALTER TABLE SURVEY_ANSWER ADD CONSTRAINT FK_SA_SURVEY FOREIGN KEY (survey_id) REFERENCES survey (id) ON DELETE CASCADE;

ALTER TABLE QUESTION_ANSWER DROP CONSTRAINT FK_QA_SURVEY_ANSWER;
ALTER TABLE QUESTION_ANSWER ADD CONSTRAINT FK_QA_SURVEY_ANSWER FOREIGN KEY (SURVEY_ANSWER_ID) REFERENCES SURVEY_ANSWER (id) ON DELETE CASCADE;
